version: '3'
services: 
  mysqlm:
    image: mysql:latest
    ports:
      - 3308:3306
    networks:
      - net-spring-db
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=factures
  micro-facture-m:
    image: facture-service
    build:
      context: .
      dockerfile: ./conteneur/Dockerfile
    depends_on:
      - mysqlm
    links:
      - mysqlm
    ports:
      - 7071:8088
    networks:
      - net-spring-db
networks:
  net-spring-db:
    driver: bridge
  